version: "3.3"

services:
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
     - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   network_mode: host
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   expose:
  #     - "5432"

volumes:
  grafana_data:
  pgdata:
